### ISSUE TITLE
关于导出微信聊天界面

### ISSUE THREAD

**Issue by no13bus** [xiaket/weixin-exporter#1]
关于导出微信聊天界面，这个程序是用在在pc上使用微信公共平台的时候 在浏览器留下cookie，来使用的吗？我在pc上直接执行py脚本，但是没成功。说是.weixin这个文件夹没有找到

**Comment by xiaket** [comment]
hi, 

  需要在电脑上通过类似iFunBox这样的工具将手机里的数据导出的.

夏 恺(Xia Kai)
http://blog.xiaket.org/

在 2013-11-16，12:08，no13bus notifications@github.com 写道：
