### ISSUE TITLE
如何查找id    id是需要在哪个文件下面找到的啊

### ISSUE THREAD

**Issue by Capricious1** [xiaket/weixin-exporter#3]

**Comment by xiaket** [comment]
Hi, 承蒙厚爱, 这个五年前因自己需求而编写的脚本现在已经不再维护. 我尽力提供一下当时做这个脚本的背景和步骤, 希望对你有帮助.

当时需要这个脚本的原因是希望自己把和我夫人的微信聊天记录打印出来, 作为配偶签证的一个proof. 当时调研了下, 没有任何地方能够提供这个服务. 但是根据一些线索, 我觉得所有这些聊天记录应该都保存到了本地, 也就是手机上. 为此, 我们需要类似iFunBox这样的工具把所有的微信数据全部复制到电脑上.

接下来, 所有的逻辑都已经在脚本里面体现了. 首先是找到对应微信号的目录, 这个在`find_target_dir`函数的注释中有介绍逻辑. 然后根据上面这个函数调用的返回值, 找到这个目录下的`DB/MM.sqlite`文件, 这个就是本地聊天记录的数据库. 具体你问到的id, 就是在这个文件里. 具体的SQL查询语句在`read_sessions`函数中有定义. 如果不确定是哪个session, 可以先查询出所有的session的行数, 这样的话你也基本上可以猜到是哪个session了.

我有很多年没有运行这个脚本了, 也不太确定上面这些步骤现在是否仍然有效. 祝好运.
